"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NavbarAdmin from "@/components/admin/NavbarAdmin";
import Footer from "@/components/footer";
import { AuthProvider, useAuth } from '../context/AuthContext';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout = ({ children }) => {
  const { user } = useAuth();

  return (
    <html lang="en">
      <body className={inter.className}>
        {user?.roles.includes("ROLE_ADMIN") ? <NavbarAdmin /> : <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default function AppRootLayout(props) {
  return (
    <AuthProvider>
      <RootLayout {...props} />
    </AuthProvider>
  );
}